name: Release
on:
  push:
    tags:
      - "*"
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 1
      - name: Create ZIP archive
        run: './scripts/release.sh'
        shell: bash
 
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            release.zip
